[colors]
background = '#181616'
foreground = '#c5c9c5'
ansi = [
  '#0d0c0c',
  '#c4746e',
  '#8a9a7b',
  '#c4b28a',
  '#8ba4b0',
  '#a292a3',
  '#8ea4a2',
  '#C8C093',
]
brights = [
  '#a6a69c',
  '#E46876',
  '#87a987',
  '#E6C384',
  '#7FB4CA',
  '#938AA9',
  '#7AA89F',
  '#c5c9c5',
]

cursor_bg = '#C8C093'
cursor_border = '#C8C093'
cursor_fg = '#c5c9c5'
selection_bg = '#2D4F67'
selection_fg = '#C8C093'

[colors.indexed]
16 = '#b6927b'
17 = '#b98d7b'

